name: Artifact Downloader Workflow

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID of the workflow to download artifact from'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Command
        id: command
        if: github.event_name == 'issue_comment'
        uses: github/command@v2.0.1
        with:
          command: .run-b
          reaction: rocket
          allowed_contexts: pull_request
          allow_forks: true
          param_separator: ' '

      - name: Set Run ID
        id: set-run-id
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "run_id=${{ inputs.run_id }}" >> $GITHUB_OUTPUT
          elif [ "${{ steps.command.outputs.continue }}" == "true" ]; then
            PARAMS="${{ steps.command.outputs.params }}"
            RUN_ID=$(echo "$PARAMS" | cut -d' ' -f2)
            if [ -z "$RUN_ID" ]; then
              echo "No run-id provided after command"
              exit 1
            fi
            echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          else
            echo "No valid run-id provided"
            exit 1
          fi

      - name: Download Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: workflow-a-artifact
          path: downloaded-artifact
          run-id: ${{ steps.set-run-id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List Downloaded Files
        run: ls -la downloaded-artifact

      - name: Read Artifact Content
        id: read-artifact
        run: |
          if [ -f downloaded-artifact/artifact.txt ]; then
            CONTENT=$(cat downloaded-artifact/artifact.txt)
            echo "content<<EOF" >> $GITHUB_OUTPUT
            echo "$CONTENT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "content=No artifact file found" >> $GITHUB_OUTPUT
          fi

      - name: Respond with Success
        if: ${{ github.event_name == 'issue_comment' && steps.command.outputs.continue == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BODY="workflowB:Artifact downloaded from run ${{ steps.set-run-id.outputs.run_id }}! \nCheck workflow logs for details.\n\nArtifact Content:\n${{ steps.read-artifact.outputs.content }}"
          gh pr comment ${{ steps.command.outputs.issue_number }} --body "$BODY"

      - name: Log Success for Manual Dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Artifact downloaded from run ${{ steps.set-run-id.outputs.run_id }}!"
          echo "Artifact Content:"
          echo "${{ steps.read-artifact.outputs.content }}"