name: Debug Python Path with Shell Flags

on:
  push:
    branches: [main]
  pull_request:

# Add concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  debug-ubuntu-latest:
    name: Debug | ubuntu-latest | Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Inspect Python (bash -ex)
        shell: bash -ex {0}
        run: |
          echo "=== Inspecting with bash -ex ==="
          echo "OS: ubuntu-latest"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

      - name: Inspect Python (bash -elx)
        shell: bash -elx {0}
        run: |
          echo "=== Inspecting with bash -elx ==="
          echo "OS: ubuntu-latest"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

  debug-ubuntu-latest-arm64:
    name: Debug | ubuntu-latest-arm64 | Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print platform.machine()
        run: |
          python -c "import platform; print(f'platform.machine(): {platform.machine()}')"
        shell: bash

      - name: Inspect Python (bash -ex)
        shell: bash -ex {0}
        run: |
          echo "=== Inspecting with bash -ex ==="
          echo "OS: ubuntu-latest-arm64"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

      - name: Inspect Python (bash -elx)
        shell: bash -elx {0}
        run: |
          echo "=== Inspecting with bash -elx ==="
          echo "OS: ubuntu-latest-arm64"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

  debug-macos-13:
    name: Debug | macos-13 | Python ${{ matrix.python-version }}
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Inspect Python (bash -ex)
        shell: bash -ex {0}
        run: |
          echo "=== Inspecting with bash -ex ==="
          echo "OS: macos-13"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

      - name: Inspect Python (bash -elx)
        shell: bash -elx {0}
        run: |
          echo "=== Inspecting with bash -elx ==="
          echo "OS: macos-13"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

  debug-macos-14:
    name: Debug | macos-14 | Python ${{ matrix.python-version }}
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Inspect Python (bash -ex)
        shell: bash -ex {0}
        run: |
          echo "=== Inspecting with bash -ex ==="
          echo "OS: macos-14"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

      - name: Inspect Python (bash -elx)
        shell: bash -elx {0}
        run: |
          echo "=== Inspecting with bash -elx ==="
          echo "OS: macos-14"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          echo "which python: $(which python)"
          echo "python --version: $(python --version)"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

  debug-windows-2019:
    name: Debug | windows-2019 | Python ${{ matrix.python-version }}
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Note: Assumes bash is available on the Windows runner (e.g., Git Bash)
      - name: Inspect Python (bash -ex)
        shell: bash -ex {0}
        run: |
          echo "=== Inspecting with bash -ex ==="
          echo "OS: windows-2019"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          # Using 'where' on Windows is more reliable than 'which'
          echo "which python: $(where python || echo 'python not found')"
          echo "python --version: $(python --version || echo 'python not found')"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"

      - name: Inspect Python (bash -elx)
        shell: bash -elx {0}
        run: |
          echo "=== Inspecting with bash -elx ==="
          echo "OS: windows-2019"
          echo "Python: ${{ matrix.python-version }}"
          echo "PATH: $PATH"
          # Using 'where' on Windows is more reliable than 'which'
          echo "which python: $(where python || echo 'python not found')"
          echo "python --version: $(python --version || echo 'python not found')"
          echo "PYTHONPATH: ${PYTHONPATH:-<not set>}"
