name: Investigate conda-build activation and CXXFLAGS

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  investigate-cxxflags:
    name: Investigate libcxx=${{ matrix.libcxx_version }}
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        libcxx_version: ["17", "14"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          miniconda-version: "latest"
          channels: defaults
          channel-priority: strict

      - name: Install conda-build and libcxx
        shell: bash -l {0}
        run: |
          echo "--- Installing conda-build and libcxx=${{ matrix.libcxx_version }} ---"
          conda install --yes -n base conda-build 'libcxx=${{ matrix.libcxx_version }}'
          echo "--- Conda Info ---"
          conda info
          echo "--- Conda List ---"
          conda list

      - name: Build conda package to check CXXFLAGS
        shell: bash -l {0}
        run: |
          mkdir recipe
          cat << EOF > recipe/meta.yaml
          package:
             name: noname
             version: 0

          source:
             path: ..

          build:
            number: 1
            script: printf "#include <cstring>\\nint main(void){};" | \$CXX \$CXXFLAGS -x c++ -v -

          requirements:
            build:
              - {{ compiler('cxx') }}
              - libcxx==${{ matrix.libcxx_version }}
          EOF

          echo "--- meta.yaml content ---"
          cat recipe/meta.yaml

          echo "--- Building conda package ---"
          conda build recipe
