name: Simple Artifact Workflow

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  create-artifact:
    name: Create and Upload Artifact
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check command
        id: command
        run: |
          if [[ "${{ github.event.comment.user.login }}" != "github-actions[bot]" && "${{ github.event.comment.body }}" == ".run-a" ]]; then
            echo "continue=true" >> $GITHUB_OUTPUT
          else
            echo "continue=false" >> $GITHUB_OUTPUT
          fi

      - name: Create artifact content
        if: ${{ steps.command.outputs.continue == 'true' }}
        run: |
          echo "Workflow-A Artifact" > artifact.txt
          echo "Triggered by .run-a command" >> artifact.txt
          echo "Commenter: ${{ github.event.comment.user.login }}" >> artifact.txt
          echo "Created at: $(date)" >> artifact.txt
          echo "Repository: ${{ github.repository }}" >> artifact.txt
          echo "Commit: ${{ github.sha }}" >> artifact.txt

      - name: Upload artifact as single file
        if: ${{ steps.command.outputs.continue == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: workflow-a-artifact
          path: artifact.txt
          retention-days: 30

      - name: Respond with Pong
        if: ${{ steps.command.outputs.continue == 'true' }}
        run: |
          BODY="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          gh pr comment ${{ github.event.issue.number }} --body "$BODY"