name: Simple Artifact Workflow

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/simple-artifact.yml'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/simple-artifact.yml'
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  debug-issue-comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment'
    steps:
      - run: |
          echo "Issue comment event triggered!"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Is PR: ${{ github.event.issue.pull_request }}"
          echo "Contains /gha run: $(echo '${{ github.event.comment.body }}' | grep -q '/gha run' && echo yes || echo no)"

  create-artifact:
    name: Create and Upload Artifact
    runs-on: ubuntu-latest
    needs: debug-issue-comment
    if: needs.debug-issue-comment.outputs.should-run == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact content
        run: |
          echo "GitHub Actions Artifact" > artifact.txt
          echo "Created at: $(date)" >> artifact.txt
          echo "Workflow: ${{ github.workflow }}" >> artifact.txt
          echo "Repository: ${{ github.repository }}" >> artifact.txt
          echo "Commit: ${{ github.sha }}" >> artifact.txt
          echo "Branch: ${{ github.ref_name }}" >> artifact.txt
          echo "Event: ${{ github.event_name }}" >> artifact.txt

          # Add comment information if triggered by comment
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "Triggered by comment: ${{ github.event.comment.body }}" >> artifact.txt
            echo "Commenter: ${{ github.event.comment.user.login }}" >> artifact.txt
          fi

          # Create a simple JSON file as well
          cat > metadata.json << EOF
          {
            "workflow": "${{ github.workflow }}",
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}",
            "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "runner": "ubuntu-latest",
            "event": "${{ github.event_name }}"
          }
          EOF

          # Add comment information to JSON if triggered by comment
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            cat > comment-metadata.json << EOF
          {
            "workflow": "${{ github.workflow }}",
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}",
            "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "runner": "ubuntu-latest",
            "event": "${{ github.event_name }}",
            "trigger": "comment",
            "comment": "${{ github.event.comment.body }}",
            "commenter": "${{ github.event.comment.user.login }}"
          }
          EOF
          fi

          # Create a directory with multiple files
          mkdir -p output
          echo "This is a sample output file" > output/sample.txt
          echo "Another file with some data" > output/data.txt

          # List what we created
          echo "Files created:"
          ls -la
          echo "Output directory contents:"
          ls -la output/

      - name: Upload artifact as single file
        uses: actions/upload-artifact@v4
        with:
          name: artifact-file
          path: artifact.txt
          retention-days: 30

      - name: Upload metadata as JSON
        uses: actions/upload-artifact@v4
        with:
          name: metadata-json
          path: metadata.json
          retention-days: 30

      - name: Upload output directory
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: output/
          retention-days: 30

      - name: Upload everything as zip
        uses: actions/upload-artifact@v4
        with:
          name: all-files
          path: |
            artifact.txt
            metadata.json
            output/
          retention-days: 30