name: Simple Artifact Workflow

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/simple-artifact.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  handle:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    steps:
      - uses: github/command@v2.0.1
        id: command
        name: command
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        with:
          command: "/gha-run-a"
          reaction: "rocket"
          allowed_contexts: pull_request
          allow_forks: true

      - name: command response
        if: steps.command.outputs.continue == 'true'
        run: |
          echo "command response"
          echo "command: ${{ steps.command.outputs.command }}"
          echo "reaction: ${{ steps.command.outputs.reaction }}"
          echo "triggered: ${{ steps.command.outputs.triggered }}"
          echo "continue: ${{ steps.command.outputs.continue }}"
          echo "issue_number: ${{ steps.command.outputs.issue_number }}"
          echo "actor: ${{ steps.command.outputs.actor }}"
          echo "fork_ref: ${{ steps.command.outputs.fork_ref }}"
          echo "ref: ${{ steps.command.outputs.ref }}"
          echo "base_ref: ${{ steps.command.outputs.base_ref }}"

      - name: checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || steps.command.outputs.ref || github.ref }}

      - name: create artifact content
        run: |
          echo "Workflow-A Artifact" > artifact.txt
          echo "Triggered by: ${{ github.event_name }}" >> artifact.txt
          if [ "${{ github.event_name }}" == "issue_comment" ] && [ "${{ steps.command.outputs.continue }}" == "true" ]; then
            echo "Command: .run-a" >> artifact.txt
            echo "Commenter: ${{ steps.command.outputs.actor }}" >> artifact.txt
          fi
          echo "Created at: $(date)" >> artifact.txt
          echo "Repository: ${{ github.repository }}" >> artifact.txt
          echo "Commit: ${{ github.sha }}" >> artifact.txt

      - name: Upload artifact as single file
        uses: actions/upload-artifact@v4
        with:
          name: workflow-a-artifact
          path: artifact.txt
          retention-days: 30

      - name: Respond with workflow run link
        if: ${{ steps.command.outputs.continue == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          BODY="Workflow completed successfully. ✅ <br> Run link: ${RUN_URL}"
          gh pr comment ${{ steps.command.outputs.issue_number }} --body "$BODY"

      - name: Respond on Failure
        if: ${{ steps.command.outputs.continue == 'false' && github.event_name == 'issue_comment' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          BODY="command failed. ❌ <br> check run logs: ${RUN_URL}"
          gh pr comment ${{ steps.command.outputs.issue_number }} --body "$BODY"